-- ============================================================================
-- 이걸주네? 초기 스키마 (API 명세서 v1 / ERD 기준)
--
-- 이 파일 이후 스키마 변경은 반드시 새 마이그레이션(V2__, V3__ ...)으로 추가한다.
-- Hibernate 는 ddl-auto: validate 로 검증만 하며 스키마를 바꾸지 않는다.
--
-- 주의: 이 마이그레이션은 "빈 스키마"를 전제로 한다.
-- Google OAuth 기반의 이전 스키마(users.google_sub, recipients 등)가 남아 있는 DB 에서는
-- Flyway 가 실행을 거부한다. 자세한 절차는 README 의 "기존 DB 에서 업그레이드" 참고.
-- ============================================================================

CREATE TABLE users (
    user_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    name          VARCHAR(100) NOT NULL,
    created_at    TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at    TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_users_email UNIQUE (email)
);

CREATE TABLE recipient (
    recipient_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT       NOT NULL,
    name         VARCHAR(100) NOT NULL,
    relationship VARCHAR(50)  NOT NULL,
    age_group    VARCHAR(30)  NOT NULL,
    gender       VARCHAR(20)  NOT NULL,
    job          VARCHAR(100),
    created_at   TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at   TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_recipient_user FOREIGN KEY (user_id) REFERENCES users (user_id)
);
CREATE INDEX idx_recipient_user_id ON recipient (user_id);

CREATE TABLE structured_preference (
    preference_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient_id     BIGINT       NOT NULL,
    preference_type  VARCHAR(50)  NOT NULL,
    preference_value VARCHAR(255) NOT NULL,
    source_type      VARCHAR(20)  NOT NULL,
    created_at       TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at       TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_preference_recipient FOREIGN KEY (recipient_id) REFERENCES recipient (recipient_id),
    -- 명세서 §13: 대상자의 동일 취향 중복 저장 방지
    CONSTRAINT uk_preference_recipient_type_value UNIQUE (recipient_id, preference_type, preference_value),
    CONSTRAINT structured_preference_preference_type_check
        CHECK (preference_type IN ('INTEREST', 'PREFERRED_CATEGORY', 'PREFERRED_ATTRIBUTE', 'DISLIKED_CATEGORY', 'WISH_ITEM')),
    CONSTRAINT structured_preference_source_type_check
        CHECK (source_type IN ('DIRECT', 'KAKAO'))
);
CREATE INDEX idx_preference_recipient_id ON structured_preference (recipient_id);

CREATE TABLE previous_gifts (
    previous_gift_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient_id     BIGINT       NOT NULL,
    gift_name        VARCHAR(255) NOT NULL,
    gift_category    VARCHAR(100),
    gifted_at        DATE,
    note             TEXT,
    created_at       TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at       TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_previous_gifts_recipient FOREIGN KEY (recipient_id) REFERENCES recipient (recipient_id)
);
CREATE INDEX idx_previous_gifts_recipient_id ON previous_gifts (recipient_id);

CREATE TABLE gift_conditions (
    condition_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient_id    BIGINT       NOT NULL,
    budget_min      INTEGER      NOT NULL,
    budget_max      INTEGER      NOT NULL,
    occasion_type   VARCHAR(100) NOT NULL,
    occasion_date   DATE,
    preference_note TEXT,
    avoid_gift_note TEXT,
    created_at      TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_gift_conditions_recipient FOREIGN KEY (recipient_id) REFERENCES recipient (recipient_id)
);
CREATE INDEX idx_gift_conditions_recipient_id ON gift_conditions (recipient_id);

CREATE TABLE recommendations (
    recommendation_id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    condition_id               BIGINT      NOT NULL,
    -- 재추천 자기참조 (명세서 §8)
    previous_recommendation_id BIGINT,
    status                     VARCHAR(20) NOT NULL,
    created_at                 TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_recommendations_condition FOREIGN KEY (condition_id) REFERENCES gift_conditions (condition_id),
    CONSTRAINT fk_recommendations_previous FOREIGN KEY (previous_recommendation_id) REFERENCES recommendations (recommendation_id),
    CONSTRAINT recommendations_status_check CHECK (status IN ('PROCESSING', 'SUCCESS', 'FAILED'))
);
CREATE INDEX idx_recommendations_condition_id ON recommendations (condition_id);

CREATE TABLE recommendation_candidates (
    candidate_id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recommendation_id     BIGINT       NOT NULL,
    gift_name             VARCHAR(255) NOT NULL,
    gift_category         VARCHAR(100),
    estimated_price_min   INTEGER,
    estimated_price_max   INTEGER,
    recommendation_reason TEXT         NOT NULL,
    considered_info       TEXT,
    caution_note          TEXT,
    recommendation_rank   INTEGER      NOT NULL,
    created_at            TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_candidates_recommendation FOREIGN KEY (recommendation_id) REFERENCES recommendations (recommendation_id),
    -- 명세서 §13: 추천 내 순위 유일 제약
    CONSTRAINT uk_candidate_recommendation_rank UNIQUE (recommendation_id, recommendation_rank)
);

CREATE TABLE feedback (
    feedback_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- 명세서 §13: 후보당 피드백 0개 또는 1개
    candidate_id   BIGINT      NOT NULL,
    feedback_type  VARCHAR(20) NOT NULL,
    dislike_reason VARCHAR(255),
    created_at     TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at     TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_feedback_candidate FOREIGN KEY (candidate_id) REFERENCES recommendation_candidates (candidate_id),
    CONSTRAINT uk_feedback_candidate_id UNIQUE (candidate_id),
    CONSTRAINT feedback_feedback_type_check CHECK (feedback_type IN ('LIKE', 'DISLIKE')),
    CONSTRAINT feedback_dislike_reason_check
        CHECK (dislike_reason IN ('TASTE_MISMATCH', 'ALREADY_OWNED', 'SIMILAR_TO_PREVIOUS', 'TOO_BURDENSOME',
                                  'NOT_PRACTICAL', 'PRICE_INAPPROPRIATE', 'WANT_DIFFERENT_STYLE', 'OTHER'))
);
