services:
  postgres:
    image: postgres:16
    container_name: ikgeoljune-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ikgeoljune
      POSTGRES_USER: ikgeoljune
      POSTGRES_PASSWORD: ikgeoljune
    ports:
      - "5432:5432"
    volumes:
      - ikgeoljune_pgdata:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d

volumes:
  ikgeoljune_pgdata:
